version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:  
  only:
  - master
configuration: Release
build_script:
- ps: .\Build.ps1
test: off  
nuget:
  disable_publish_on_pr: true
artifacts:
- path: .\**\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: c18PmLObjM4XzNKNj8/LzYty11gya98+IerJXipzMmL9wgmHS6cGAJWYpJkDxmU2
  on:
    branch: master
    appveyor_repo_tag: true